### PR TITLE
Fix iCubBlinker compilation against yarp 3.6

### LINKED ISSUE #22: iCubBlinker compilation failure against YARP-3.6
Since https://github.com/robotology/yarp/pull/2780 has been merged, `funny-things` is failing with this error:
~~~
2021-12-22T16:04:29.7621615Z -- Build files have been written to: /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things
2021-12-22T16:04:37.1402008Z [235/248] Performing build step for 'funny-things'
2021-12-22T16:04:37.1403659Z FAILED: src/funny-things/CMakeFiles/YCMStamp/funny-things-build /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/CMakeFiles/YCMStamp/funny-things-build 
2021-12-22T16:04:37.1406115Z cd /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things && /usr/bin/cmake --build . && /usr/bin/cmake -E touch /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/CMakeFiles/YCMStamp/funny-things-build
2021-12-22T16:04:37.1407593Z [1/10] Generating code from iCubBlinker.thrift
2021-12-22T16:04:37.1408531Z [2/10] Building CXX object modules/iCubBreather/CMakeFiles/iCubBreather.dir/iCubBreatherModule.cpp.o
2021-12-22T16:04:37.1409786Z [3/10] Building CXX object modules/iCubBreather/CMakeFiles/iCubBreather.dir/iCubBreatherThread.cpp.o
2021-12-22T16:04:37.1410864Z [4/10] Building CXX object modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/main.cpp.o
2021-12-22T16:04:37.1411610Z [5/10] Linking CXX executable bin/iCubBreather
2021-12-22T16:04:37.1412181Z [6/10] Running utility command for copy_lua_in_build
2021-12-22T16:04:37.1412965Z [7/10] Building CXX object modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o
2021-12-22T16:04:37.1413921Z FAILED: modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o 
2021-12-22T16:04:37.1417364Z /usr/bin/c++  -I/__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/modules/iCubBlinker -isystem /__w/robotology-superbuild/robotology-superbuild/build/install/include -g -std=c++1z -MD -MT modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o -MF modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o.d -o modules/iCubBlinker/CMakeFiles/iCubBlinker.dir/iCubBlinker_IDL.cpp.o -c /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/modules/iCubBlinker/iCubBlinker_IDL.cpp
2021-12-22T16:04:37.1420920Z /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/modules/iCubBlinker/iCubBlinker_IDL.cpp:17:11: error: "'blink_fast' will never be called, since 'blink' starts with the same tag"
2021-12-22T16:04:37.1422404Z  YARP_COMPILER_ERROR("'blink_fast' will never be called, since 'blink' starts with the same tag")
2021-12-22T16:04:37.1423012Z            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-12-22T16:04:37.1424418Z /__w/robotology-superbuild/robotology-superbuild/build/src/funny-things/modules/iCubBlinker/iCubBlinker_IDL.cpp:18:11: error: "'blink_naturalistic' will never be called, since 'blink' starts with the same tag"
2021-12-22T16:04:37.1425976Z  YARP_COMPILER_ERROR("'blink_naturalistic' will never be called, since 'blink' starts with the same tag")
2021-12-22T16:04:37.1426627Z            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-12-22T16:04:37.1427333Z [8/10] Building CXX object modules/funnyPostures/CMakeFiles/funnyPostures.dir/main.cpp.o
2021-12-22T16:04:37.1428109Z ninja: build stopped: subcommand failed.
~~~

fyi @randaz81 @S-Dafarra @pattacini @Nicogene @drdanz

### PR DESCRIPTION
**Pull request by Nicogene**
It fixes #22

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Note that we may want to mention this change in the changelog of the release, as it seems that a few other repos (see https://github.com/robotology/attention/search?q=blink, fyi  omareldardear) used the `blink` command that is now removed.

**Comment by traversaro** [comment]
Other code affected:
* https://github.com/icub-tech-iit/appsAway/blob/d407f3405f5743bd1c0a7c54338c9bbf0cf89775/demos/funnyThingsApp/script/funnythings_template.sh#L64 fyi @vtikha

**Review by pattacini — APPROVED** [review]

**Comment by Nicogene** [comment]
>     https://github.com/icub-tech-iit/appsAway/blob/d407f3405f5743bd1c0a7c54338c9bbf0cf89775/demos/funnyThingsApp/script/funnythings_template.sh#L64 fyi @vtikha

This should be addressed by the changes in this PR.

Do you mean we should add a changelog in this repo?

**Comment by traversaro** [comment]
> > ```
> > https://github.com/icub-tech-iit/appsAway/blob/d407f3405f5743bd1c0a7c54338c9bbf0cf89775/demos/funnyThingsApp/script/funnythings_template.sh#L64 fyi @vtikha
> > ```
> 
> 
> This should be addressed by the changes in this PR.

Ah sorry, I did not see this.

> Do you mean we should add a changelog in this repo?

No, even just mentioning it in the releases notes it is ok for me.

**Pull request merged**
